version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run: # ここでシェルが立ち上がる
          name: test_kure
          command: |
            pwd # /home/circleci/project
            ls
