version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run: echo "hello world"
      - run: unamae -a
      - run: ruby -v
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
