version: 2.1
jobs:
  job1:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: echo "hello world"
      - run: uname -a
      - run: ruby -v
      - run: bundle -v
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
