version: 2.1
commands:
  say_hello:
    steps:
      - run: echo "hello from commands"
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run: echo "hello world"
      - say_hello

