version: 2.1
workflows:
  build:
    jobs:
      - function1
      - function2
  build2:
    jobs:
      - function1
jobs:
  function1:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          working_directory: lib/function1
      - run:
          name: rspec
          command: bundle exec rspec
          working_directory: lib/function1
  function2:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
          working_directory: lib/function2
      - run:
          name: rspec
          command: bundle exec rspec
          working_directory: lib/function2
