version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.3
    steps:
      - checkout
      - run: echo "hoge"
      - run:
          name: run script
          command: |
            chmod u+x ./lib/test.sh
            ./lib/test.sh
      - run:
          name: Create Dummy File
          command: |
            echo "Create File"
            echo "111111111" > /tmp/hoge
            mkdir /tmp/hoge1
            echo "222222222" > /tmp/hoge1/hoge
            mkdir /tmp/hoge2
            echo "333333333" > /tmp/hoge2/hoge
      - store_artifacts:
         path: /tmp
         destination: "code-coverage"
