version: 2.1
commands:
  say_hello:
    steps:
      - run: echo "hello from commands"
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: Kure Test
          command: echo "kure test"
      - run:
          command: |
            echo "command1"
            echo "command2"
            ls
            pwd
            whoami
      - say_hello

