version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - run: echo "hoge"
      - run:
        name: Create Dummy File
        command: |
          echo "Create File"
          echo "hogehgoe" > /tmp/hoge
      - store_artifacts:
        path: /tmp/hoge
