version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: ~/lib/function1
    steps:
      - checkout
      - run: echo "hello world"
      - run:
        name: pwd
        command: pwd
        working_directory: lib/function1
      - run:
        name: ls
        command: ls
        working_directory: lib/function1
      - run:
        name: bundle install
        command: bundle install --path vendor/bundle
        working_directory: lib/function1
      - run: bundle exec rspec
