version: 2.1
commands:
  command1:
    steps:
      - run: # ここでシェルが立ち上がる
          name: test_kure2
          command: |
            pwd # /home/circleci/project
            echo 'from commands'
jobs:
  build:
    docker:
      - image: cimg/ruby:4.0.7
    steps:
      - checkout
      - run: # ここでシェルが立ち上がる
          name: test_kure
          command: |
            ls
            pwd # /home/circleci/project
            echo 'jobs'
            echo "hoge $(date)" >> hoge.txt
            git config user.name  "circleci"
            git config user.email "circleci@example.com"
            git add hoge.txt
            git commit -m "update hoge.txt [skip ci]"
            git push origin HEAD
      - command1
