version: 2.1
executors:
  my-exe:
    docker:
      - image: circleci/ruby:2.6.5
commands:
  say_hello:
    steps:
      - run: echo "hello from commands"
workflows:
  version: 2
  build:
    jobs:
      - job1
      - job2
jobs:
  job1:
    executor:
      name: my-exe
    steps:
      - checkout
      - run: echo "hello world"
      - say_hello

  job2:
    executor:
      name: my-exe
    steps:
      - checkout
      - run: echo "hello world"
      - say_hello
    
