version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - run: echo "hoge"
      - run:
          name: run script
          command: |
            chmod u+x ./lib/test.sh
            ./lib/test.sh
      - run:
          name: Create Dummy File
          command: |
            echo "Create File"
            echo "hogehgoe" > /tmp/hoge
      - store_artifacts:
         path: /tmp/hoge
