# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "dotenv", "2.7.6"
gem "rspec"
gem "aws-sdk-ec2", "1.195.0"
gem "aws-sdk-s3", "1.67.1"
gem "slack-notifier", "2.3.0"
