version: 1
update_configs:
 # - package_manager: "ruby"
 #   directory: "/"
 #   update_schedule: "weekly"
  - package_manager: "ruby:bundler"
    directory: "/lambda_function1/src/"
    update_schedule: "weekly"
