name: create_pr_release_to_master
on:
  push:
    branches:
      - release
jobs:
  create_pr_release_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "本番リリース用PRです"
          pr_body: "本日リリースの PR です。\nマージの向き先が release -> master になっていることを確認して、問題無ければマージして下さい。"
          pr_draft: true
          pr_label: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
