name: create_pr_master_to_develop
on:
  push:
    branches:
      - master
jobs:
  create_pr_master_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "リリースで発生した変更を develop ブランチへ反映します"
          pr_body: "リリースで発生した変更を develop ブランチへ反映するため、master -> develop のマージをします。"
          pr_label: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
